version: "3"
services:
    nginx:
      restart: always
      build: ./nginx
      ports:
        - "0.0.0.0:8081:80"
      links:
        - app:app
    app:
        build: ./ucubot
        ports:
            - "80:8080"
        depends_on:
            - db
    db:
        image: "mysql:5.7"
        environment:
            MYSQL_ROOT_PASSWORD: "1qaz2wsx"
            ACCEPT_EULA: "Y"
